[package]
name = "subvol"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "31corefs-subvol"
path = "src/main.rs"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5", features = ["derive"] }
lib31corefs = { path = "../../lib31corefs" }
