[package]
name = "subvol"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "31corefs-subvol"
path = "src/main.rs"

[dependencies]
chrono.workspace = true
clap.workspace = true
fs31core.workspace = true
