[package]
name = "dump"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["31core 31core@tutanota.com"]

[[bin]]
name = "31corefs-dump"
path = "src/main.rs"

[dependencies]
chrono.workspace = true
clap.workspace = true
fs31core.workspace = true
uuid.workspace = true
