[package]
name = "mkfs"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["31core 31core@tutanota.com"]

[[bin]]
name = "31corefs-mkfs"
path = "src/main.rs"

[dependencies]
clap.workspace = true
fs31core.workspace = true
